[package]
name = "arbitrage"
version = "0.1.0"
edition = "2024"
dependencies = "A development framework focused on arbitrage."

[dependencies]
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }